### PR TITLE
Make ShouldNotBeNull chainable and unwrap System.Nullable

### LINKED ISSUE #559: ShouldHaveValue() for chainable assertions on nullable values
This a common pattern:

```cs
foo.Bar.ShouldNotBeNull();
foo.Bar.Value.X.ShouldBe(42);
foo.Bar.Value.Name.ShouldBe("bar");
foo.Bar.Value.Date.ShouldBe(Jan3);

baz.Bar.ShouldNotBeNull();
baz.Bar.Value.Date.ShouldBe(Jan4);
```

I would like to be able to remove the `foo.Bar.Value` repetition, which requires a Should method that returns the unpacked value just like `.ShouldHaveSingleItem()` does:

```cs
var bar = foo.Bar.ShouldHaveValue();
bar.X.ShouldBe(42);
bar.Name.ShouldBe("bar");
bar.Date.ShouldBe(Jan3);

baz.Bar.ShouldHaveValue().Date.ShouldBe(Jan4);
```

`.Value` would be fine except that I want a Shouldly error message if it's something that would be expected to break if the test fails.

https://github.com/shouldly/shouldly/issues/271 was closed because the second method would have no advantage over `ShouldBeNull()`.

### PR DESCRIPTION
**Pull request by jnm2**
Closes #559 (supersedes the design)

I noticed that the new ShouldHaveValue() method would be completely identical to the struct variant of ShouldNotBeNull that we already ended up with. Instead of adding a new method, I augmented the existing ones. Making ShouldNotBeNull chainable for reference types was already on my wish list.

```cs
int unwrapped = ((int?)42).ShouldNotBeNull();
string worksWithNRTsToo = ((string?)"42").ShouldNotBeNull();
```

### CODE REVIEW

**Comment by jnm2** [comment]
@JosephWoodward @SimonCropp @slang25 The master branch is failing. Should we consider protecting it so that it can't be updated except via PRs that pass CI?

**Comment by SimonCropp** [comment]
@jnm2 sorry the broken build is my fault. will look into it now

> Should we consider protecting it so that it can't be updated except via PRs that pass CI?

I am on the fence. but happy to go with the consensus

**Review by SimonCropp — COMMENTED** [review]
can some docs be added for this change?

**Comment by JosephWoodward** [comment]
> @JosephWoodward @SimonCropp @slang25 The master branch is failing. Should we consider protecting it so that it can't be updated except via PRs that pass CI?

I'm not so fussed personally. Whilst we should try our best not to break master, there's not enough change going through it which would mean it's broken for long.

File: src/Shouldly/ShouldlyExtensionMethods/ShouldBeNullExtensions.cs [hunk 1]
```diff
@@ -26,19 +26,17 @@ public static void ShouldBeNull<T>([MaybeNull] this T? actual, string? customMes
         }
 
         [ContractAnnotation("actual:null => halt")]
-        public static void ShouldNotBeNull<T>([NotNull] this T? actual, string? customMessage = null)
+        public static T ShouldNotBeNull<T>([NotNull] this T? actual, string? customMessage = null)
```
Comment (RodgerLeblanc) [inline src/Shouldly/ShouldlyExtensionMethods/ShouldBeNullExtensions.cs:29]: Don't you want to return `T?` instead of `T`, even if it has the `NotNullAttribute` and that it will throw if the value is `null`?

It seems weird that a fluent method is not returning the same type as its parameter, meaning that the chained assertion will be performed on a different type.

For example, this won't compile : 
`((int?)0).ShouldNotBeNull().ShouldNotBeNull();`

Comment (jnm2) [reply src/Shouldly/ShouldlyExtensionMethods/ShouldBeNullExtensions.cs:29]: Thanks for the question! No, the motivation in #559 was specifically to unwrap nullable values. I have a lot of code asserts that a struct is not null and then asserts things about several deeper properties. Having to repeat `.Value` is onerous. There are code examples in #559 that show examples.

(This is also why we petitioned for C# 8's coalescing assignments to unwrap nullable values. The original design did not; it made you do `(nullableFoo ??= GetFoo()).Value`. Having to say `.Value` on a thing that is never null is noisy and frustrating. Thankfully, they listened and changed it before C# 8 shipped!)

I see it as a feature that `((int?)0).ShouldNotBeNull().ShouldNotBeNull();` doesn't compile, in line with https://github.com/shouldly/shouldly/issues/584, and I like the parallel with nullable reference types.

**Comment by jnm2** [comment]
@SimonCropp Happy to, what kind of docs were you thinking? Adding something to DocumentationExamples, or something else?

**Comment by SimonCropp** [comment]
>Adding something to DocumentationExamples

yep, and including those snippets into the markdown

**Comment by jnm2** [comment]
@SimonCropp What do you do to generate the anchor IDs in the markdown?

File: src/Shouldly/ShouldlyExtensionMethods/ShouldBeNullExtensions.cs (hunk 1 above)
Comment (jnm2) [reply src/Shouldly/ShouldlyExtensionMethods/ShouldBeNullExtensions.cs:29]: Another longstanding example of an assertion method that returns a different type is ShouldHaveSingleItem.

**Comment by SimonCropp** [comment]
they will be updated on build https://github.com/SimonCropp/MarkdownSnippets

**Comment by jnm2** [comment]
@SimonCropp I tried a few things based on https://github.com/SimonCropp/MarkdownSnippets, but `dotnet build src` and `dotnet test src` don't seem to be updating it. What am I missing?

**Comment by jnm2** [comment]
Looks like the master branch is broken again due to merging https://github.com/shouldly/shouldly/pull/681.

**Comment by SimonCropp** [comment]
>  I tried a few things based on https://github.com/SimonCropp/MarkdownSnippets, but dotnet build src and dotnet test src don't seem to be updating it. What am I missing?

Not sure. i think just merge this, and i will debug the doco

And i fixed the build

**Comment by SimonCropp** [comment]
@jnm2 is this ready to be merged?

**Comment by jnm2** [comment]
Yes, and it needs the doc tooling followup after merge that you mentioned.
